services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    ports:
    - "8080:80"
    links:
      - php-fpm
#      - node

  php-fpm:
    build:
      context: ./docker/php/dev/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
#    depends_on:
#      - mailhog
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "MAILER_DSN=smtp://mailhog:1025"
    links:
      - mysql
#      - node

#  php-cli:
#    build:
#      context: ./docker/php/dev/php-cli
#      dockerfile: Dockerfile
#    volumes:
#    - ./:/var/www
#    environment:
#      - "DB_PORT=3306"
#      - "DB_HOST=mysql"
#      - "REDIS_PORT=6379"
#      - "REDIS_HOST=redis"
#      - "COMPOSER_MEMORY_LIMIT=-1"
#    links:
#      - mysql
#    tty: true

  mysql:
    image: mysql:8.0
    volumes:
    - ./DBDocker:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=12345678"
      - "MYSQL_DATABASE=symfony"
    ports:
        - "3306:3306"

#  node:
#    image: node:18-alpine
#    ports:
#        - "3000:3000"
#    volumes:
#    - ./:/var/www
#    working_dir: /var/www
#    tty: true

  redis:
    image: redis:latest
    ports:
        - "6379:6379"

#  mailhog:
#      image: mailhog/mailhog
#      container_name: mailhog
#      ports:
#          - "8025:8025"
#          - "1025:1025"


    ###> symfony/mailer ###
#  mailer:
#      image: axllent/mailpit
#      ports:
#          - "1025"
#          - "8025"
#      environment:
#          MP_SMTP_AUTH_ACCEPT_ANY: 1
#          MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
